### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by janakan97** [ioangatop/super_tml#2]
Why this method cannot be regression why this method only focus on the classification. Is it able to make the code to accept all kind of  tabular dataset rather only focusing the iris and wine

**Comment by ioangatop** [comment]
Obviously by modifying the loss function, the model can also tackle regression tasks. The premise of this repo is to prove a concept (recreation of the results from the scientific paper) and with the proper modifications can be extended to accept any tabular data. Any merge requests with additional functionalities / modifications are welcome!
